version: "3.8"

services:
  warehouse-backend:
    image: warehouse-backend:latest
    container_name: warehouse-backend
    build:
      context: .
      dockerfile: ./backend/docker/deployment/Dockerfile
    volumes:
      - ./backend:/warehouse-backend
    env_file:
      - backend/docker/dev.env
    ports:
      - 88:88
    depends_on:
      - mongo

  warehouse-frontend:
    image: warehouse-frontend:latest
    container_name: warehouse-frontend
    build:
      context: .
      dockerfile: ./frontend/deploy/docker/Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

  mongo:
    image: mongo:latest
    restart: always
    container_name: warehouse_mongo
    hostname: mongo.docker
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
